minesweepers/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using minesweepers.Models;
using NHibernate.Linq;
using PagedList;

namespace minesweepers.Controllers
{
	public class EntryController : BaseController
	{
		public ActionResult Index(int? page)
		{
			var pageIndex = (page ?? 1) - 1; //MembershipProvider expects a 0 for the first page
			var pageSize = 20;
			var pageNumber = page ?? 1;

			var paged = session.Query<SearchEntry>();

			var list = session.Query<SearchEntry>().ToPagedList(pageNumber, pageSize);

			return View(list);
		}

		public ActionResult Details(int id)
		{
			return View();
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(SearchEntry entry)
		{
			try
			{
				if (ModelState.IsValid)
				{
					using (var trans = session.BeginTransaction())
					{
						session.SaveOrUpdate(entry);
						trans.Commit();
					}
				}

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		//
		// GET: /Entry/Edit/5

		public ActionResult Edit(int id)
		{
			var entry = session.Get<SearchEntry>(id);
			return View(entry);
		}

		//
		// POST: /Entry/Edit/5

		[HttpPost]
		public ActionResult Edit(int id, FormCollection collection)
		{
			try
			{
				if (ModelState.IsValid)
				{
					using (var trans = session.BeginTransaction())
					{
						var entry = session.Get<SearchEntry>(id);
						if (TryUpdateModel(entry))
						{
							session.SaveOrUpdate(entry);
							trans.Commit();
						}
					}
				}

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		//
		// GET: /Entry/Delete/5

		public ActionResult Delete(int id)
		{
			var entry = session.Get<SearchEntry>(id);
			return View(entry);
		}

		//
		// POST: /Entry/Delete/5

		[HttpPost]
		public ActionResult Delete(int id, FormCollection collection)
		{
			try
			{
				if (ModelState.IsValid)
				{
					using (var trans = session.BeginTransaction())
					{
						var entry = session.Get<SearchEntry>(id);
						session.Delete(entry);
						trans.Commit();
					}
				}

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

minesweepers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/jquery-1.8.2.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/jquery-ui-1.9.0.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
</head>
<body>
	<div class="page">
		<header>
						<div id="title">
								<h1>@Html.ActionLink("Cyberminer", "Index", "Home")</h1>
						</div>
						<div id="logindisplay">
								by MindSweepers
						</div>
						<nav>
								<ul id="menu">
										<li>@Html.ActionLink("Home", "Index", "Home")</li>
										<li>@Html.ActionLink("Entries", "Index", "Entry")</li>
								</ul>
						</nav>
				</header>
		<section id="main">
						@RenderBody()
				</section>
		<footer>
				</footer>
	</div>
</body>
</html>